### ISSUE TITLE
HTTP/1.1 500 Server Error

### ISSUE THREAD

**Issue by canewsin** [jeppeman/LocallyDynamic#9]
```
2020-03-30 11:23:08: Server started at http://192.168.42.170:51562/
2020-03-30 11:23:08: Username: cb5013d317734a8d8d99bd03a0f02ac5
2020-03-30 11:23:08: Password: 1f7b912a11a540b1b01f1c626334b807
2020-03-30 11:23:08: Storage backend initialized: LocalStorageBackend(baseStoragePath=C:\Users\PramUkesh\Documents\FlutterProj\zeronet_mobile\android\build)
2020-03-30 11:23:08: Https redirects enabled: false
2020-03-30 11:23:08: DownloadSplitsPathHandler registered for path /download
2020-03-30 11:23:08: RegisterDevicePathHandler registered for path /register
2020-03-30 11:23:08: UploadBundlePathHandler registered for path /upload
2020-03-30 11:23:08: LivenessPathHandler registered for path /liveness_check
2020-03-30 11:23:35: <-- POST http://192.168.42.170:51562/upload
2020-03-30 11:23:35: Request-IP: 192.168.42.170
2020-03-30 11:23:35: Authorization: Basic Y2I1MDEzZDMxNzczNGE4ZDhkOTliZDAzYTBmMDJhYzU6MWY3YjkxMmExMWE1NDBiMWIwMWYxYzYyNjMzNGI4MDc
2020-03-30 11:23:35: Connection: keep-alive
2020-03-30 11:23:35: User-Agent: Apache-HttpClient/4.5.6 (Java/1.8.0_212-release)
2020-03-30 11:23:35: Host: 192.168.42.170:51562
2020-03-30 11:23:35: Accept-Encoding: gzip,deflate
2020-03-30 11:23:35: Content-Length: 289950618
2020-03-30 11:23:35: Content-Type: multipart/form-data; boundary=jDGDG-wDi9uThu20eBM2qs3urJa_wI3GdiBujqdk
2020-03-30 11:23:47: --> 200 POST http://192.168.42.170:51562/upload
```

I'm Using Flutter SDK to build android apps
build path is different from above
> C:\Users\PramUkesh\Documents\FlutterProj\zeronet_mobile\build

I think this is causing the issue.

**Comment by jeppeman** [comment]
Can you include the error too?

**Comment by canewsin** [comment]
that is the only line i got

**Comment by jeppeman** [comment]
It says 200 in the server logs you attached, where do you get the 500 from?

**Comment by canewsin** [comment]
In the buildoutput tab

**Comment by jeppeman** [comment]
Can you run the build with `--stacktrace` appended?

**Comment by canewsin** [comment]
i was running --scan output now, i will publish it when done.

**Comment by canewsin** [comment]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileProfileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileProfileKotlin'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.api.GradleException: Compilation error. See log for more details
        at org.jetbrains.kotlin.gradle.tasks.TasksUtilsKt.throwGradleExceptionIfError(tasksUtils.kt:14)
        at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.run(GradleKotlinCompilerWork.kt:122)
        at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.runCompilerAsync(GradleKotlinCompilerRunner.kt:148)
        at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.runCompilerAsync(GradleKotlinCompilerRunner.kt:143)
        at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.runJvmCompilerAsync(GradleKotlinCompilerRunner.kt:83)
        at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompilerAsync$kotlin_gradle_plugin(Tasks.kt:429)
        at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompilerAsync$kotlin_gradle_plugin(Tasks.kt:339)
        at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.executeImpl(Tasks.kt:296)
        at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.execute(Tasks.kt:268)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskInputsTaskAction.doExecute(IncrementalTaskInputsTaskAction.java:47)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
        at org.gradle.api.internal.project.taskfactory.AbstractIncrementalTaskAction.execute(AbstractIncrementalTaskAction.java:25)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:476)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$0(ExecuteStep.java:32)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:32)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
        ... 34 more


* Get more help at https://help.gradle.org

BUILD FAILED in 59s
560 actionable tasks: 554 executed, 6 up-to-date
```

**Comment by jeppeman** [comment]
This appears to be unrelated

**Comment by canewsin** [comment]
i think it is related to build folder path, as i stated in first comment.

**Comment by jeppeman** [comment]
Could be, but that stack trace is showing a compiler error from `:app:compileProfileKotlin`, which is something different. Could you do the following:
```
cd C:\Users\PramUkesh\Documents\FlutterProj\zeronet_mobile\android
./gradlew bundleDebug
```

And then attach the entire build log if it fails

**Comment by canewsin** [comment]
I try with blank project, and report it.

**Comment by canewsin** [comment]
```
> Task :app:uploadLocallyDynamicBundleDebug FAILED
Failed to upload bundle, make sure the server is running and is reachable at http://192.168.42.170:62765/, reason:
HTTP/1.1 500 Server Error
         *********************************************************
WARNING: This version of flutter_webview_plugin will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:uploadLocallyDynamicBundleDebug'.
> org.apache.http.HttpException: HTTP/1.1 500 Server Error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 48s
```


Locally Dynamic Log
```
2020-03-31 14:28:31: Username: deb9c7c56490417286afc83a9218a007
2020-03-31 14:28:31: Password: 774880f4dc6b4392882be93811988641
2020-03-31 14:28:31: Storage backend initialized: LocalStorageBackend(baseStoragePath=C:\Users\PramUkesh\Documents\FlutterProj\zeronet_mobile\android\build)
2020-03-31 14:28:31: Https redirects enabled: false
2020-03-31 14:28:31: DownloadSplitsPathHandler registered for path /download
2020-03-31 14:28:31: RegisterDevicePathHandler registered for path /register
2020-03-31 14:28:31: UploadBundlePathHandler registered for path /upload
2020-03-31 14:28:31: LivenessPathHandler registered for path /liveness_check
2020-03-31 14:28:31: <-- POST http://192.168.42.170:62765/upload
2020-03-31 14:28:31: Request-IP: 192.168.42.170
2020-03-31 14:28:31: Authorization: Basic ZGViOWM3YzU2NDkwNDE3Mjg2YWZjODNhOTIxOGEwMDc6Nzc0ODgwZjRkYzZiNDM5Mjg4MmJlOTM4MTE5ODg2NDE
2020-03-31 14:28:31: Connection: keep-alive
2020-03-31 14:28:31: User-Agent: Apache-HttpClient/4.5.6 (Java/1.8.0_121)
2020-03-31 14:28:31: Host: 192.168.42.170:62765
2020-03-31 14:28:31: Accept-Encoding: gzip,deflate
2020-03-31 14:28:31: Content-Length: 289948626
2020-03-31 14:28:31: Content-Type: multipart/form-data; boundary=2RGElJ9QjuHdSfGaN6sDnxtf3LtO_i8VooKhVLZc
2020-03-31 14:28:31: --> 200 POST http://192.168.42.170:62765/upload
```

**Comment by jeppeman** [comment]
Thanks, was this with a blank flutter project?

**Comment by canewsin** [comment]
no its existing do you need a blank one ?

**Comment by jeppeman** [comment]
Just need a way to reproduce it so I can see what is actually happening on the server

**Comment by canewsin** [comment]
Minimal Repo
https://github.com/canewsin/dynamic_feature_assets

**Comment by jeppeman** [comment]
Thank you! I'll have a look tonight

**Comment by jeppeman** [comment]
Found the issue, it is an `OutOfMemoryError` - that is why it doesn't appear in the LocallyDynamic Log as well. I will fix within the next couple of days and let you know

**Comment by canewsin** [comment]
Is there any update regarding this ?

**Comment by jeppeman** [comment]
Working on it, should be done this afternoon

**Comment by jeppeman** [comment]
The update should be available in Android Studio now (version 0.3). Let me know if you run into any problems

**Comment by canewsin** [comment]
```
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: 
Could not find com.jeppeman.locallydynamic.gradle:plugin:0.3.
```

**Comment by canewsin** [comment]
ok I got it, I have to update AS plugin.
